# Binary Search and AVL Trees
Built framework for both types of trees. Below is an outline of the structure:

Container: Parent class with Insert, Find, Remove

BST: Basic Binary Search Tree

AVL: Self-Balancing AVL Search Tree


Emperical Testing: To analyze the impact of AVL Trees, we tested both trees with random, unsorted words, and then again with sorted words. See analysis document for more.
